/**
 * APK Config - Auto-generated from APK (layout + resources)
 * Sources: activity_activation.xml, colors.xml, strings.xml, dimens.xml, AnimationConstants.kt, SplashActivity.kt, ActivationActivity.kt, WaveView.kt, res/anim/*.xml, res/drawable/*.xml, res/font/*
 * Regenerate: .\extract-apk-values.ps1
 */
const APK_CONFIG = {
  colors: {
    theme_primary: '#00ff88',
    theme_primary_light: '#00ff88',
    theme_primary_dark: '#00cc6a',
    theme_hint_neon: '#8000ff88',
    theme_border: '#4D00ff88',
    theme_border_light: '#8000ff88',
    status_error: '#F44336',
    button_text_dark: '#000000',
    activation_background: '#0a0a0a',
  },
  strings: {
    app_name_title: 'FASTPAY',
    app_tagline: 'The Real Gaming Platform',
    status_label: 'STATUS',
    step_validate: '• IP Connection Established',
    activation_title: 'ACTIVATION',
    running: 'RUNNING',
    step_register: '• Request Sent / Compatibility test',
    crypto_hash_label: '#123 ALWAYS SECURE',
    sha256_badge: 'SHA256',
    activate: 'ACTIVATE',
    retry_status: 'Retrying in 5s...',
    testing: 'TESTING',
    retry_now: 'RETRY NOW',
    step_auth: '• Authorization Check (Approved / Denied)',
    step_sync: '• Response Decrypted',
    activation_status: 'Creating secure tunnel with company database',
    clear: 'CLEAR',
    hint_phone_testing: 'Enter Your Phone Number',
    hint_code_running: 'Enter Your Bank Code',
    reset: 'Reset',
  },
  dimens: {
    center_content_padding_top: '32dp',
    center_content_padding_horizontal: '16dp',
    input_height: '72dp',
    input_padding_horizontal: '16dp',
    input_text_size: '18sp',
    button_height: '64dp',
    button_margin_top: '32dp',
    splash_letter_size: '64sp',
    tagline_text_size: '12sp',
    tagline_margin_top: '8dp',
    logo_text_size: '38sp',
  },
  animation: {
    button_press_scale_down_ms: 100,
    button_press_scale_up_ms: 150,
    input_focus_scale_duration_ms: 200,
    input_focus_scale: 1.02,
    shake_duration_ms: 400,
    hint_char_delay_ms: 80,
    loading_button_duration_ms: 4000,
    splash_total_duration_ms: 6000,
    splash_fade_out_ms: 300,
    wave_duration_ms: 2000,
    wave_start_remaining_ms: 2000,
    entry_stagger_ms: 150,
    entry_duration_ms: 600,
    recede_duration_ms: 350,
    recede_scale: 0.85,
    recede_alpha: 0.4,
  },
  grid: { type: 'RADIAL', size: 50, opacity: 0.1, duration_ms: 10000 },
  scanline: { duration_ms: 2000, height: 3 },
  anim: {
    fade_in: { duration_ms: 400, interpolator: 'decelerate_interpolator', fromAlpha: 0, toAlpha: 1 },
    neon_pulse: { duration_ms: 2000, interpolator: 'accelerate_decelerate_interpolator', fromAlpha: 0.8, toAlpha: 1.0, repeatCount: 'infinite' },
    pulse: { duration_ms: 1000, repeatCount: 'infinite' },
    slide_up: { duration_ms: 600, interpolator: 'decelerate_interpolator', fromAlpha: 0, toAlpha: 1 },
  },
  drawables: {
    button_activate_solid: { type: 'solid', color: '#00ff88' },
    button_clear_outlined: { type: 'solid', color: '#80000000' },
    button_reset_background: { type: 'solid', color: '#00000000' },
    button_test_background_enhanced: { type: 'solid', startColor: '#1A00ff88', endColor: '#00000000', centerColor: '#0D00ff88', color: '@android:color/transparent', angle: 135 },
    crypto_hash_card_background: { type: 'solid', startColor: '#00000000', endColor: '#00000000', centerColor: '#1500ff88', color: '#051a1a1a', angle: 135, gradientType: 'linear' },
    gradient: { type: 'gradient', startColor: '#0a0a0a', endColor: '#0a0a0a', angle: 90, gradientType: 'linear' },
    gradient2: { type: 'gradient', startColor: '#0a0a0a', endColor: '#1a1a1a', angle: 90, gradientType: 'linear' },
    input_field_selector: { type: 'solid', color: '@android:color/transparent' },
    instruction_card_background_light_green: { type: 'solid', color: '#E6F7E9' },
    login_type_button_background: { type: 'solid', color: '@android:color/transparent' },
    login_type_divider: { type: 'solid', color: '#4D00ff88' },
    login_type_selector_background: { type: 'solid', color: '@android:color/transparent' },
    overlay_glass_background: { type: 'solid', color: '#E6000000' },
    sha256_badge_background: { type: 'solid', color: '#80000000' },
    sms_count_badge_background: { type: 'solid', color: '#3300ff88' },
  },
  fonts: {
    families: ['aoboshi_one', 'inter', 'inter_semibold'],
  },
};
